### ISSUE TITLE
Change AuthenticationService::authenticate to return an object 

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/authentication#227]
AuthenticationService::authenticate returns an array with 'request', 'response' and 'result'.
I think we should return an object with methods 'getResponse', 'getRequest', 'getResult' and 'getAllResults', this could help with php type hint and IDE's auto-completion.

The new class could be named as AuthenticationData, or something similar.

```
<?php
class AuthenticationData
{
    /**
     * Gets the authentication result.
     *
     * @return \Authentication\Authenticator\ResultInterface|null Authentication result interface
     */
    public function getResult()
    {

    }

    /**
     * Gets all authentication results.
     *
     * @return \Authentication\Authenticator\ResultInterface[] list of authentication results
     */
    public function getAllResults()
    {

    }

    /**
     * Gets the possible modified response object.
     *
     * @return \Psr\Http\Message\ResponseInterface response possible modified
     */
    public function getResponse()
    {

    }

    /**
     * Gets the possible modified request object.
     *
     * @return \Psr\Http\Message\ServerRequestInterface request possible modified
     */
    public function getRequest()
    {

    }
} 
```

What do you think?

**Comment by markstory** [comment]
Sounds reasonable to me. @burzum @robertpustulka ?

**Comment by rochamarcelo** [comment]
It may not change the request but the response may change like in CookieAuthenticator, right?

**Comment by robertpustulka** [comment]
@rochamarcelo Phauthentic implementation does not take the response. The request/response handling takes place in persistIdentity and cleatIdentity methods.

**Comment by rochamarcelo** [comment]
I see, so to keep a similar API the authenticate method should not persist the identity, the middleware must call persistIdentity after success authenticate right? Also What is the plan to do it?

**Comment by rochamarcelo** [comment]
> Note that the lib we ported (Phauthentic/authentication) returns `bool` now: https://github.com/Phauthentic/authentication/blob/master/src/AuthenticationServiceInterface.php#L32
> 
> `authenticate()` method never modifies the request so there's no need to return it. The service there is stateful, so you can get the successful result and all the failed ones from the service.
> 
> If we would like to move to the Phauthentic at some point, we probably need to keep a similar API.

By the way, what is the reason for this port? Why not implements the changes on cakephp/authentication?

**Comment by robertpustulka** [comment]
The plan was to implement framework agnostic lib with PSR-15 support which CakePHP middleware is not compatible with. There is cake adapter for phauthentic though which might become 2.0 of this plugin at some point.

**Comment by burzum** [comment]
@rochamarcelo the CakePHP adapter can be found here https://github.com/Phauthentic/authentication-cakephp

The library approach resolves a lot of hard dependencies and allowed us to write the code in fashion CakePHP currently doesn't allow because we're stuck to what Cake wants. The password hashers were extracted in yet another separate library. For example I prefer the option setter methods A LOT over the config arrays. A config object would work as well. With an IDE you get auto discovery and docs of the options as you type and you can't do anything wrong. An array with a simple typo can become a PITA to debug if you don't see it right after you've made it. Also being able to drop the locators was just nice. I'm obviously biased because I worked on both, this implementation and then on the Phauthentic version, but I like the none cake version much much more.

**Comment by dereuromark** [comment]
Closing then as no plan of attack necessary at this point.
