### ISSUE TITLE
setIdentity() not updating session database table on login

### ISSUE THREAD

**Issue by stephengalbraith** [cakephp/authentication#263]
Hi there,

I have been trying for the past few hours to get the Authentication plugin working for some basic needs. I have come to the point that I want to update the session's user data on login (to include some other data such as a user's roles).

Below is my login action from UsersController:

```
$result = $this->Authentication->getResult();
        if ($result->isValid()) {
            $identity = $this->request->getAttribute('identity');

            $user = $this->Users->findById($identity['id'])->contain(['Roles'])->first();
            
            $this->Authentication->setIdentity($user);
            
            $identity = $this->Authentication->getIdentity();
            
            $redirect = $this->request->getQuery('redirect', ['controller' => 'users', 'action' => 'index']);
            return $this->redirect($redirect);
        }
        
        if ($this->request->is(['post']) && !$result->isValid()) {
            $this->Flash->error('Invalid username or password');
        }
```

I haven't made any major modifications to the implementation of the Authentication plugin and followed the docs exactly as laid out.

The error I am getting is `$this->Authentication->setIdentity($user);` not updating the database session. If I do a var_dump or print_r before the redirect on logging in, the data is all there, but it does not persist to another page.

This is likely not much to go on, but I am getting no errors, but can provide any other code as requested. I am on the latest v. 4.x-dev for the app and 2.x-dev for the plugin.

**Comment by markstory** [comment]
Do other session updates persist properly? There has been one other related issue https://github.com/cakephp/cakephp/issues/13018 are you in a similar situation with php-fpm?

**Comment by stephengalbraith** [comment]
If I clear the table and simply load the page the new session is created with the default data. If I login, it identifies me properly, but only trying to get the new user data doesn't get saved.

And sorry, I am not sure about php-fpm.

**Comment by markstory** [comment]
Ok. I'll see if I can reproduce this issue.

**Comment by markstory** [comment]
I tried reproducing this locally with file based sessions as wasn't able to. In the previously linked issue the reporter was running into latency issues between the web & database servers. Could you see if you have a similar issue by switching to file based sessions?

**Comment by stephengalbraith** [comment]
I tried that with no success.

@markstory I hope you don't mind but I send you a gist link on Slack to a list of the files I have that relate to this.

**Comment by markstory** [comment]
I was able to track this problem down to a0e492ff. In this diff the authentication result is re-written to the session on lines 129-131 to ensure the identity is persisted. This write overwrites the one you've done in your application.

You could likely fix this problem by setting the `finder` option on the `resolver` for your `Form` authenticator. The third example in [this section](https://book.cakephp.org/authentication/1.1/en/migration-from-the-authcomponent.html#migrate-authcomponent-settings) shows how to configure the resolver your identifiers use. Instead of `userModel` you can use `finder` to use a custom finder on your `UsersTable` class that loads the required association allowing you to skip the additional queries and calls to `setIdentity()` entirely.

**Comment by stephengalbraith** [comment]
The above resolved my issue. Thank you again!
