### ISSUE TITLE
README example use statements

### ISSUE THREAD

**Issue by dereuromark** [cakephp/authentication#36]
Should we add the use statements for
https://github.com/cakephp/authentication#configuration
etc?

I think some beginners might need them.

**Comment by burzum** [comment]
Well, if you don't know that or can't handle the error you'll get when you forgot them, you should learn php first and OOP before trying a php framework?

But if you like to add them.

**Comment by dereuromark** [comment]
We usually do so everywhere, and in the docs. And while I agree with you, it might still keep us from a few unnecessary question tickets opened :)

**Comment by markstory** [comment]
> Well, if you don't know that or can't handle the error you'll get when you forgot them, you should learn php first and OOP before trying a php framework?

Its easy to forget that lots of people that use Cake are new to PHP and programming.

> I'm not a fan of spoon-feeding lazy people with exhaustive examples because it's no help. 

Attitudes like this don't help us reach more people. Instead the foster an elitist feeling, that I don't think helps the project.

**Comment by inoas** [comment]
In general: I do think we should advocate reading the PHP manual, at least. This will help newbies and reduce self-solvable questions on IRC/slack.

Concrete: I don't think the use statements hurt and many of them can be found throughout the docs. Especially when there is a class available but it is the wrong one due to the lack of using namespaces/use statements correctly, newbies can be thrown off.

**Comment by burzum** [comment]
> Its easy to forget that lots of people that use Cake are new to PHP and programming.

This doesn't make my statement less true? It's like as if I want to speak Chinese and start with whole sentence without knowing the grammar and just 5 words. Sometimes you need to tell people to start with the basics.

> Attitudes like this don't help us reach more people. Instead the foster an elitist feeling, that I don't think helps the project.

You forgot to quote the important part of my text. This is not about being elite it's about how you teach stuff so that your students have a benefit as well. You gain nothing from spoon-feeding, nor your students do. This is also an attitude you need to cultivate in your students. I can show my students all day how they have to make a certain move or technique, if they never understood the principles due to the fact they resist to do so or they didn't understood them they'll keep failing in applying that move. You need to teach people how to learn and how to work with learning material first sometimes. This is what I want people and my students to understand first. Once they've got that point they'll master everything else mostly alone.

However, point taken, put as much examples in the docs as you wish as long as I don't have to write them. ;)

**Comment by xavier83ar** [comment]
While I agree with @burzum, I think that it says much about the quality and richness of the documentation, when you see an example of code that "looks" like it work, it should work, ideally, if it doesn't work (maybe because of missing lines, typos, etc.) It creates a bad impression even on those people that have expertise and can fix the issue. 

Further more, as @dereuromark pointed out, it's done like this everywhere on the docs, and I think that having a homogenous documentation it's a good practice.

**Comment by harikt** [comment]
Proper working examples are always good. So if you are not adding use statements use FQNS.
