### ISSUE TITLE
AuthenticationComponent getIdentity fails in ErrorController

### ISSUE THREAD

**Issue by chyt** [cakephp/authentication#415]
I have an `ErrorController` that extends my app's main `AppController`. In the `AppController.initialize` function I retrieve the user identity using `$this->Authentication->getIdentity()` and use it throughout my application. 

This works fine, except when an exception is thrown that triggers the `ErrorController`. The `ErrorController` calls `AppController.initialize` in its own `initialize` function. I can see that `AppController.initialize` is being executed in the `ErrorController`, except the call to `$this->Authentication->getIdentity()` returns no identity even when the user is logged in.

Looking at the underlying implementation, I wonder if it could have something to do with the fact that it is relying on a request attribute? But I'm not sure how to resolve this, or if it is intentional behavior. I could not find any docs on this issue.

**Comment by markstory** [comment]
Because requests are immutable, the error handling middleware does not see the user that is added to the request in the authentication middleware. Even if requests were mutable, your application error handling code would still need to treat the user as optional, as there are many ways an exception could be raised before a user could be added to the request.

>  I wonder if it could have something to do with the fact that it is relying on a request attribute? 

Yes the combination of requests being immutable and the user being an attribute is contributing to this situation. One potential resolution is to put the error handling middleware *after* the authenication middleware. While this would help with this scenario you'd still need to treat the user as optional because you'd be relying on the global exception handler as well.
