### ISSUE TITLE
Credential challenge headers not sent to client for HttpBasic and HttpDigest authenticators

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#48]
While the authenticator for http basic and digest authenticator have `unauthenticated()` method for throwing `UnauthorizedException` with the challenge headers this method is never called by the authentication service.

Similarly for other stateless authenticator like `TokenAuthenticator` there's no mechanism to return a response with 401 code. So even if authentication fails the controller action is accessible.

**Comment by markstory** [comment]
Perhaps the fix for this could be related to #47? If instead of using a Cake HTTP exception we could use a new state `Result::FAILURE_HARD_FAILURE/FAILURE_CHALLENGE_REQUIRED` to signal to the `AuthenticationService` that the current authenticator its unauthenticated() method called so it can prepare a `ChallengeException`. The middleware could handle this exception and use the headers/body in the exception to update the response and return it instead of calling the next middlware layer. This would be a pattern similar to how `Router` handles redirect routes.

**Comment by ADmad** [comment]
Yeah fixing this would take care of #47 too. Your suggestion on how to handle this sounds good.

**Comment by markstory** [comment]
I'll try to put together a solution.

**Comment by markstory** [comment]
Closing as #50 is open.
