### ISSUE TITLE
RFC:  Rename OrmIdentifier to ORMIdentifier and proposed JwtAuthenticator to JWTAuthenticator

### ISSUE THREAD

**Issue by ADmad** [cakephp/authentication#53]
It's better to use caps for the acronyms. In namespace too we use `ORM` and pretty much every JWT relates classes I have seen in other libs use `JWT` in the name.

**Comment by dereuromark** [comment]
I would rather stick with the normal CamelCase naming convention (JwtAuthenticator, OrmIdentifier) we use so far for all core classes and all ecosystem tools, including the core plugins Acl and CO.
True, the ORM namespace is a small expection, but it is also just a namespace.
The rest, especially 100% of all classes are following the convention, though, including:

- [AclComponent](https://github.com/cakephp/acl/blob/master/src/Controller/Component/AclComponent.php) (ACL)
- [CrudAuthorize](https://github.com/cakephp/acl/blob/master/src/Auth/CrudAuthorize.php) (CRUD)
- JsonView
- HtmlHelper
- Js and Css stuff in AssetCompress
- CsvView, RssView, ...

Starting sth different now is a small flake naming in the middle of an otherwise quite consistent naming scheme IMO.

**Comment by burzum** [comment]
I agree with @ADmad argumentation but I also agree with @dereuromark. Either we have them all changes or we stick to the current pattern. We could consider changing this in CakePHP 4.

**Comment by inoas** [comment]
I think we should not get into the hell of deciding if something is an abbreviation or not.
While the PHP docs use for example XMLFoo, Symfony and CakePHP use XmlFoo: http://symfony.com/doc/current/components/serializer.html

**Comment by ADmad** [comment]
Closing, it's no biggie.
