### ISSUE TITLE
Improve identifier errors

### ISSUE THREAD

**Issue by cleptric** [cakephp/authentication#84]
Currently, when an Identifier can't find a user, it just returns `null`, which leads into an error array with no explanation of what went wrong in the return of `authenticate()`.

```
[
    'Authentication.Orm' => []
]
```

Maybe we can add sth like:

```
[
    'Authentication.Token' => [],
    'Authentication.Orm' => [
        'No user was found' // e.g.
    ]
]
```

**Comment by ADmad** [comment]
An identifier not returning an entity isn't exactly an error condition since the next identifier in the list could return one.

**Comment by ADmad** [comment]
That's said the identifiers could set msg like `No identify found` when returning null. Skimming the code I didn't find any case in which an identifier sets error message currently.

**Comment by burzum** [comment]
@ADmad this was your idea and as far as I understood you - and I agree with - is the errors array mostly thought for things that aren't covered by the statuses. I don't think the error error needs to be filled with the status we already cover in the result object. So for example if I try to authenticate against LDAP and the LDAP server returns an error, this error should go into the error array because it's not covered by the default statuses the result object already communicates.

**Comment by burzum** [comment]
@ADmad whats your opinion on that? :)

**Comment by ADmad** [comment]
We could try to document this first and if we still get reports expecting a message then do so :)

**Comment by burzum** [comment]
@ADmad see https://github.com/cakephp/authentication/pull/90

**Comment by burzum** [comment]
Closing this because we have a PR up for it.
